model_name: "GSAI-ML/LLaDA-8B-Instruct"    # 预训练模型名称
local_batch_size: 1                              # 训练批次大小
max_length: 4096                           # 分词最大长度
num_epochs: 20                             # 训练轮数
learning_rate: 1e-5                        # 优化器学习率
grad_accum_steps: 1                        # 梯度累积步数
output_dir: "./sft_save"                   # 模型与日志保存目录
job_name: "llada-sft"                       # 任务名称
train_data: "simplescaling/s1K"  # 训练数据路径